apiVersion: apps/v1
kind: Deployment
metadata:
  name: nmr
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: nmr
  template:
    metadata:
      labels:
        app: nmr
    spec:
      containers:
        - name: nmr
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: MODEL_DIR
              value: "/app/models/transformer_reg"
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
