apiVersion: v1
kind: Service
metadata:
  name: nmr
spec:
  selector:
    app: nmr
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 8000
  type: {{ .Values.service.type }}
